### ISSUE TITLE
Question about this project

### ISSUE THREAD

**Issue by pidgeon777** [ravsii/tree-sitter-d2#3]
Hello, thanks for your interesting project.

I would like to kindly ask how it would compare to this:

https://git.pleshevski.ru/pleshevskiy/tree-sitter-d2

I see the above repository also got some recent updates.

Moreover, does your repository include all of the bugfixes/features of that one also?

Cheers

**Comment by ravsii** [comment]
Hi @pidgeon777

This started as a replacement for Pleshivskiy's project because it barely worked for my use case (his grammar was unable to parse basic stuff, shown in the docs). Unfortunately, my need for D2 is long gone, and I was developing it during my free time.  

It sort of works and has tests for **all** the examples in the [docs](https://d2lang.com/tour/intro/) — shapes, connections, containers, text & code, images, SQL, and sequence diagrams. For really basic use cases, it's more or less usable. However, I haven't implemented any queries, so there's no highlighting out of the box — only parsing.  

If I had at least _some_ experience with grammar parsers, it would probably be finished already. But I still encounter problems where one new construction breaks everything.

**Comment by pidgeon777** [comment]
Thank you for the detailed explanation. Hopefully someone will continue your work 👍.
